// GENERATED by scratchpad/round5_patch.py: which sources each page and section cites.
export type SourcePage = { title: string; href: string; blurb: string; sections: { title: string; ids: string[] }[] };

export const sourceMap: SourcePage[] = [
  {
    title: "Home",
    href: "/",
    blurb: "The upgrade, highlights, the net-loss timeline and status",
    sections: [
      { title: "Hero, what it is, speed and cost", ids: ["render", "notice", "sob", "cba", "dcd-pipeline", "waterpdf", "faq", "sweden", "bloom-co2", "bloom-chart", "nmelc", "nmsu", "epwater", "twdb", "cduaws", "haussamen-water", "cbd-well", "epm-jobs"] },
      { title: "Who are you (audience panels)", ids: ["cba", "epm-jobs", "county-qa", "nmsu", "sob", "sunland-park-ozone", "ala-sota-2025", "dailylobo", "haussamen-water", "cbd-well", "epa-watersense", "render", "sweden", "nmpr-stay", "bloom-chart", "doe-pv-cost"] },
      { title: "Highlights", ids: ["bocc", "econpdf", "cba", "nmsu", "faq", "county-qa", "epm-jobs", "sob", "sunland-park-ozone", "ala-sota-2025", "bloom-chart", "bloom-fuels", "haussamen-water", "cbd-well", "epa-watersense"] },
      { title: "Two Jupiters", ids: ["sob", "sunland-park-ozone", "photo-grs"] },
      { title: "Net loss, year after year", ids: ["sob", "bocc", "cba", "cbd-well", "haussamen-water", "nmsu", "sunland-park-ozone", "ala-sota-2025", "epa-ozone-naaqs", "epm-jobs", "sweden", "notice", "carrier-furnace", "render"] },
      { title: "Updates and status tracker", ids: ["cba", "nmpr-stay", "abq-stay", "notice", "cbd-well", "slo", "energyconnects", "abq-reports", "bocc"] },
    ],
  },
  {
    title: "Blueprint",
    href: "/blueprint",
    blurb: "Site plan, five processes, costs, timeline",
    sections: [
      { title: "The site plan", ids: [] },
      { title: "Process 1. Heat", ids: ["render", "waterpdf", "faq", "sob", "sweden", "carrier-furnace", "cba"] },
      { title: "Process 2. Carbon", ids: ["sob", "epa-ozone-naaqs", "sunland-park-ozone", "nmelc", "epa-pm-naaqs", "notice", "bloom-co2", "bloom-chart", "bocc", "abq-lc", "cba", "epa-class-vi-saline", "bloom-fuels", "faq", "ala-sota-2025", "epa-class-vi"] },
      { title: "Process 3. Water", ids: ["nmsu", "epwater", "twdb", "cduaws", "cba", "faq", "haussamen-water", "cbd-well", "epa-watersense", "usgs-mesilla", "bocc"] },
      { title: "Process 4. Solar: roof by roof on the blueprint", ids: ["ktsm-sqft", "notice", "render", "cba", "doe-pv-cost"] },
      { title: "Process 5. Greenhouses", ids: ["cba", "epm-jobs", "sob", "sweden", "waterpdf", "render", "faq", "spread-keihanna", "chengdu-vertical", "vf-energy", "vf-econ"] },
      { title: "Click-to-explain part panels", ids: ["render", "ktsm-sqft", "faq", "waterpdf", "notice", "photo-phe", "sweden", "carrier-furnace", "cba", "epm-jobs", "nmsu", "dcd-pipeline", "slo", "energyconnects", "bloom-fuels", "bocc", "sob", "sfnm-fuelcells", "bloom-co2", "bloom-chart", "nmelc", "sunland-park-ozone", "ala-sota-2025", "epa-ozone-naaqs", "epa-pm-naaqs", "epa-class-vi-saline", "epa-class-vi", "usgs-induced", "decatur", "cduaws", "cbd-well", "haussamen-water", "photo-bgndrf", "epwater", "twdb", "sfnm-water", "usgs-mesilla", "doe-pv-cost"] },
      { title: "Glossary", ids: ["carrier-furnace", "eia-homes", "notice", "epa-watersense", "epa-ozone-naaqs", "epa-pm-naaqs", "sob", "cduaws", "bloom-chart", "cba", "county-qa", "sunland-park-ozone"] },
      { title: "Timeline", ids: ["cba", "bocc", "sob", "cbd-well", "slo", "sourcenm-moratorium", "dailylobo", "nmpr-stay", "abq-stay", "abq-reports", "nmsu", "bloom-fuels"] },
    ],
  },
  {
    title: "Science",
    href: "/science",
    blurb: "The engineering, at four reading levels",
    sections: [
      { title: "Key components", ids: ["render", "notice", "sob", "cba", "dcd-pipeline", "waterpdf", "faq", "sweden", "bloom-co2", "bloom-chart", "nmelc", "nmsu", "epwater", "twdb", "cduaws", "haussamen-water", "cbd-well", "epm-jobs"] },
      { title: "Reading levels: the numbers with sources", ids: ["cba", "epm-jobs", "faq", "county-qa", "econpdf", "bocc", "notice", "carrier-furnace", "waterpdf", "sweden", "nmsu", "sob", "nmelc", "bloom-co2", "bloom-chart", "bloom-fuels", "epa-class-vi-saline", "epa-class-vi", "usgs-induced", "epa-ozone-naaqs", "epa-pm-naaqs", "sunland-park-ozone", "ala-sota-2025", "cduaws", "epwater", "twdb", "haussamen-water", "cbd-well", "epa-watersense", "ktsm-sqft", "doe-pv-cost", "render"] },
    ],
  },
  {
    title: "Legislators",
    href: "/legislators",
    blurb: "Bills, sponsors and the ask",
    sections: [
      { title: "The three bills and the record they answer", ids: ["dailylobo", "sourcenm-moratorium", "cba", "nmpr-stay", "abq-reports", "commissioners"] },
    ],
  },
  {
    title: "Petition",
    href: "/petition",
    blurb: "The five conditions",
    sections: [
      { title: "The five conditions and what they rest on", ids: ["cba", "sob", "bloom-chart", "nmsu", "sweden", "sunland-park-ozone"] },
    ],
  },
  {
    title: "FAQ",
    href: "/faq",
    blurb: "Their questions, answered with sources",
    sections: [
      { title: "Whole page", ids: ["sfnm-fuelcells", "sob", "bloom-chart", "faq", "sunland-park-ozone", "ala-sota-2025", "epa-ozone-naaqs", "notice", "bocc", "cba", "bloom-fuels", "haussamen-water", "cbd-well", "nmsu", "epm-jobs", "sfnm-water", "usgs-mesilla", "abq-reports", "econpdf"] },
    ],
  },
];
